version: "3.9"
services:
  server:
    build: 
      context: ./Ml-model\ and\ Backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./Ml-model\ and\ Backend:/app
  
  web:
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/user/src/app
    depends_on:
      - server
